# Generated by Django 5.0.3 on 2024-03-21 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='category_photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='product_images'),
            preserve_default=False,
        ),
    ]
