# Generated by Django 5.0.3 on 2024-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_cartitem_cart_remove_cartitem_item_cartmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='total_price',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
    ]
